### ISSUE TITLE
Add ARCHITECTURE.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by utzcoz** [boringdroid/boringdroid#4]
Add basic `ARCHITECTURE.md` and `CONTRIBUTING.md`

**Comment by anandhi25** [comment]
Hello, 
I want to ask, how i can implement minimize button for each window, and provides a smooth resizing experience in Android 11 desktop mode source code?

Thank you

**Comment by utzcoz** [comment]
> Hello,
> I want to ask, how i can implement minimize button for each window, and provides a smooth resizing experience in Android 11 desktop mode source code?
> 
> Thank you

See this commit 
https://github.com/boringdroid/platform_frameworks_base/commit/cfea5d7594a8908a7a6d79702406c65a22728d08.
